kind: ConfigMap
apiVersion: v1
metadata:
  name: azuredns-config
  namespace: traefik
data:
  AZURE_CLIENT_ID: 8edf0602-b9c0-4322-bf34-802e4f3add7d
  AZURE_SUBSCRIPTION_ID: 1c766f37-8740-4764-932c-bf96cbb29a39
  AZURE_DNS_ZONE: titiler.water-gis.com
  AZURE_RESOURCE_GROUP: undpdpbppssdganalyticsgeo