---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titiler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titiler
  template:
    metadata:
      labels:
        app: titiler
    spec:
      containers:
        - name: titiler
          image: ghcr.io/undp-data/titiler-aks:v0.0.1
          resources:
            limits:
              memory: "2048Mi"
              # cpu: "900m"
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: WORKERS_PER_CORE
              value: "1"
            - name: API_CORS_ORIGIN
              value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: titiler
  labels:
    app: titiler
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8000
  selector:
    app: titiler
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: titiler-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`titiler.undpgeohub.org`)
      kind: Rule
      services:
        - name: titiler
          port: 80
