additionalArguments:
  - "--accesslog=true"
  - "--accesslog.format=json"
  - "--log.level=DEBUG"

deployment:
  replicas: 1

service:
  spec:
    loadBalancerIP: "13.81.173.247"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: undpdpbppssdganalyticsgeo
